name: this is my first github action project

on:
 push:
  branches: [ "main" ]

jobs:
 build:
  runs-on: ubuntu-latest

  strategy:
   matrix: 
    python-version: [3.8, 3.9]


  steps:
  - uses: actions/checkout@v4
  - name: jdk environment setup
    uses: actions/setup-java@v4
    with:
     java-version: '17'
     distribution: 'temurian'
     cache: maven

  - name: build with maven
    run:
     mvn package --file pom.xml

  - name: upload artifact
    uses: actions/upload-artifact@v4
    with:
     name: broadridge
     path: target/*.jar

  - name: scan the repo with trivy
    run:
     trivy fs --format table -o trivy-fs-report.html

  - name: adding sonarqube details
    uses: sonarsource/sonarqube-scan-action@master
    env:
     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  - name: install json query
    run:
     sudo apt-get update && sudo apt-get install -y jq


  - name: sonar qube quality gate check
    id: sonarqube-quality-gate-check
    timeout-minutes: 5
    env:
     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  - name: setup QEMU for docker
    uses: docker/setup-qemu-action@v3

  - name: setup docker buildx
    uses: docker/setup-buildx-action@v3

  - name: build docker image
    run:
     docker build -t Narendar12/Github-actions:latest .

  - name: docker image scan with trivy
    run:
     trivy image --format table -o trivy-image-report.html Narendar12/Github-actions:latest

  - name: login to docker hub
    uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: push docker image
    run:
     docker push Narendar12/Github-actions:latest 

  - name: deploy app to kubernetes cluster
    uses: tale/kubectl-action@v1
    with:
     base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    run:
     kubectl apply -f deployment.yaml -n webapps


  
    
  

     
  
      
    
    
    

     
     

    
    
