name: mt first github action
on:
 push:
  branches: [ "main" ]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4
  - name: provide permission to file
    working-directory: examples/src
    run: chmod +x my_script.sh
  - name: execute shell script
    working-directory: examples/src
    run: ./my_script.sh

    
  

  

    
  

    



  



