name: my first github action

on:
 push:
  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: provide access to script
      working-directory: examples/src
      run: chmod +x my_script.sh
    - name: to run the script
      run: ./my_script.sh

  

    
  

    



  



